version: '3.1'

services:
    app:
        build: .
        container_name: app
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        environment:
            - DB_USER=olesia
            - DB_PASSWORD=123
            - DB_URL=jdbc:postgresql://db:5432/db
        depends_on:
          - db

    db:
        image: postgres
        container_name: db
        ports:
            - "5433:5432"
        environment:
            POSTGRES_PASSWORD: 123
            POSTGRES_USER: olesia
            POSTGRES_DB: db